<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://webservices" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://webservices" xmlns:intf="http://webservices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://webservices" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="obtenerBoxMedicos">
    <complexType/>
   </element>
   <element name="obtenerBoxMedicosResponse">
    <complexType>
     <sequence>
      <element name="obtenerBoxMedicosReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="obtenerBoxMedicosRequest">

      <wsdl:part element="impl:obtenerBoxMedicos" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="obtenerBoxMedicosResponse">

      <wsdl:part element="impl:obtenerBoxMedicosResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="BoxWS">

      <wsdl:operation name="obtenerBoxMedicos">

         <wsdl:input message="impl:obtenerBoxMedicosRequest" name="obtenerBoxMedicosRequest">

       </wsdl:input>

         <wsdl:output message="impl:obtenerBoxMedicosResponse" name="obtenerBoxMedicosResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="BoxWSSoapBinding" type="impl:BoxWS">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="obtenerBoxMedicos">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="obtenerBoxMedicosRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="obtenerBoxMedicosResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="BoxWSService">

      <wsdl:port binding="impl:BoxWSSoapBinding" name="BoxWS">

         <wsdlsoap:address location="http://localhost:8080/ProveedorServicioHospital/services/BoxWS"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
