<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://webservices" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://webservices" xmlns:intf="http://webservices" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://webservices" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="obtenerMedicos">
    <complexType/>
   </element>
   <element name="obtenerMedicosResponse">
    <complexType>
     <sequence>
      <element name="obtenerMedicosReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="obtenerMedicosResponse">

      <wsdl:part element="impl:obtenerMedicosResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="obtenerMedicosRequest">

      <wsdl:part element="impl:obtenerMedicos" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="MedicoWS">

      <wsdl:operation name="obtenerMedicos">

         <wsdl:input message="impl:obtenerMedicosRequest" name="obtenerMedicosRequest">

       </wsdl:input>

         <wsdl:output message="impl:obtenerMedicosResponse" name="obtenerMedicosResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="MedicoWSSoapBinding" type="impl:MedicoWS">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="obtenerMedicos">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="obtenerMedicosRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="obtenerMedicosResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="MedicoWSService">

      <wsdl:port binding="impl:MedicoWSSoapBinding" name="MedicoWS">

         <wsdlsoap:address location="http://localhost:8080/ProveedorServicioHospital/services/MedicoWS"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
